In [9]:

import TextProcessing
import DataCollecting
import DataProcessing

import warnings
warnings.filterwarnings("ignore")

DATASET = "data.csv"

tp = TextProcessing.TextProcessor()

imdb = DataCollecting.IMDBSurfer(DataCollecting.OMDB_API_KEY, None, [DATASET])

dp = DataProcessing.DataProcessor(tp, None, DATASET)

In [11]:
import pandas as pd
imdb.search_not_present_movies([
    "Terminator"
])
imdb.results
imdb.write_to_csv("new-data.csv")
new = pd.read_csv("new-data.csv")
new

Terminator is already in the results. Skipping...
Results written to new-data.csv.

,Title,Year,Genre,Description
0,Terminator,1991,"Short, Action, Sci-Fi","A cyborg comes from the future, to kill a girl..."

In [12]:
new["Keywords"] = new["Description"].apply(tp.extract_keywords)

In [13]:
dp.load_dataframe()

Data Processor DataFrame loaded from: data.csv

In [14]:
dp.add_rows_of_dataframe(new)

Rows added successfully.

In [15]:
dp.sync_dataframe_with_dataset()

DataFrame synced to data.csv

In [16]:
dp.dataframe[dp.dataframe["Title"] == "Terminator"]

,Title,Year,Genre,Description,Keywords
210,Terminator,1991,"Short, Action, Sci-Fi","A cyborg comes from the future, to kill a girl...","[cyborg, semen, future, killing, girl, name, S..."